text_api_key = "your  Azure Text Analytics api here"
text_endpoint = "your  Azure Text Analytics service endpoint here"
vision_api_key = "your  Azure vision api here"
vision_endpoint = "your  Azure vision endpoint here"
speech_subscription_key  = "your  Azure speech api here"
speech_region = "Your azure resorce here"
subscription_key  = "Your azure bing search api here"
search_url  = "youe bing search search_url (or) end_point here"